### ISSUE TITLE
fail to install pytorch_quantization 

### ISSUE THREAD

**Issue by wendy0527** [NVIDIA-AI-IOT/Lidar_AI_Solution#134]
when I want to  pip install pytorch-quantization:
************************************************************************
Collecting pytorch-quantization
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/35/ea/c6c4ab73da4e36b9eddea7ff687b98e1bccb59bfb3bd0c24459914fb17f2/pytorch-quantization-0.0.1.dev5.tar.gz (7.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-czw5iwjz/pytorch-quantization_7e3c42ea0b53427192ecc459e7ead477/setup.py", line 150, in <module>
          raise RuntimeError(open("ERROR.txt", "r").read())
      RuntimeError:
      ###########################################################################################
      The package you are trying to install is only a placeholder project on [PyPI.org](http://pypi.org/) repository.
      This package is hosted on NVIDIA Python Package Index.

      This package can be installed as:
      ```
      $ pip install nvidia-pyindex
      $ pip install pytorch-quantization
      ```
      ###########################################################################################

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
***********************************************************************************************************************
But I have successfully installed nvidia-pyindex, through pip install nvidia-pyindex

**Comment by hopef** [comment]
https://github.com/NVIDIA/TensorRT/tree/release/8.6/tools/pytorch-quantization
