### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'data'

### ISSUE THREAD

**Issue by qq160816** [NVIDIA-AI-IOT/Lidar_AI_Solution#185]
I run "python tool/dump-data.py" output error.

Please tell me why?

Traceback (most recent call last):
  File "tool/dump-data.py", line 97, in <module>
    dump_tensor(args)
  File "tool/dump-data.py", line 49, in dump_tensor
    dataset = build_dataset(cfg.data.test)
  File "/home/wangweilin/anaconda3/envs/bevfusion_mit/lib/python3.8/site-packages/mmcv/utils/config.py", line 507, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/wangweilin/anaconda3/envs/bevfusion_mit/lib/python3.8/site-packages/mmcv/utils/config.py", line 48, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'data'

**Comment by sangjinpark97** [comment]
Literally config file you use has no attribute 'data'.
You need to check the config argument.

**Comment by qq160816** [comment]
> Literally config file you use has no attribute 'data'. You need to check the config argument.

I used c++ to save data is ok.
Thank you!
