### ISSUE TITLE
CUDA-Centerpoint: convert .pth to .onnx error

### ISSUE THREAD

**Issue by chenxyyy** [NVIDIA-AI-IOT/Lidar_AI_Solution#70]
Hi! Thank you for your work.

I have trained a weight in Nuscense and I want to use cuda-centerpoint for interference，but when I **convert the .pth file to .onnx**， I have met many errors.

### 1. export-scn.py (Failed)

```Bash
python onnx_export/export-scn.py  --ckpt work_dirs/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z/latest.pth  --save-onnx centerpoint.scn.onnx
```

I met  the following error.

```Bash
🔥export original model🔥
Traceback (most recent call last):
  File "onnx_export/export-scn.py", line 72, in <module>
    model = funcs.load_scn_backbone_checkpoint(model, args.ckpt, use_quant =False)
  File "/data/pointcloud_alg/Lidar_AI_Solution-master/CenterPoint-master/onnx_export/funcs.py", line 98, in load_scn_backbone_checkpoint
    model.load_state_dict(new_ckpt,strict =True)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SpMiddleResNetFHD:
        size mismatch for conv_input.0.weight: copying a param with shape torch.Size([5, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 5]).
        size mismatch for conv1.0.conv1.weight: copying a param with shape torch.Size([16, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
        size mismatch for conv1.0.conv2.weight: copying a param with shape torch.Size([16, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
        size mismatch for conv1.1.conv1.weight: copying a param with shape torch.Size([16, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
        size mismatch for conv1.1.conv2.weight: copying a param with shape torch.Size([16, 16, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([16, 3, 3, 3, 16]).
        size mismatch for conv2.0.weight: copying a param with shape torch.Size([16, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 16]).
        size mismatch for conv2.3.conv1.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
        size mismatch for conv2.3.conv2.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
        size mismatch for conv2.4.conv1.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
        size mismatch for conv2.4.conv2.weight: copying a param with shape torch.Size([32, 32, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 3, 3, 3, 32]).
        size mismatch for conv3.0.weight: copying a param with shape torch.Size([32, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 32]).
        size mismatch for conv3.3.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for conv3.3.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for conv3.4.conv1.weight: copying a param with shape torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for conv3.4.conv2.weight: copying a param with shape torch.Size([64, 64, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 3, 3, 3, 64]).
        size mismatch for conv4.0.weight: copying a param with shape torch.Size([64, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 64]).
        size mismatch for conv4.3.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
        size mismatch for conv4.3.conv2.weight: copying a param with shape torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
        size mismatch for conv4.4.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
        size mismatch for conv4.4.conv2.weight: copying a param with shape torch.Size([128, 128, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 3, 3, 3, 128]).
        size mismatch for extra_conv.0.weight: copying a param with shape torch.Size([128, 128, 3, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 3, 1, 1, 128]).
```

Then I found the `onnx_export/export-scn.py`, I made the following changes.  It can work now.

```Python
def load_scn_backbone_checkpoint(model, file, use_quant= True):

    device   = next(model.parameters()).device
    ckpt     = torch.load(file, map_location=device)["state_dict"]
    new_ckpt = collections.OrderedDict()
    for key, val in ckpt.items():
        if key.startswith("backbone."):
            newkey = key[key.find(".")+1:]
            # if use_quant == False:                      # Here is my change!!!
            #   if val.ndim == 5:
            #        val = val.permute(4, 0, 1, 2, 3)

            new_ckpt[newkey] = val

    model.load_state_dict(new_ckpt,strict =True)
    return model
```

But when the program reached this point, a new error occurred.

```Python
def export_onnx(model, voxels, coors, batch_size, spatial_shape, save_onnx, save_tensor):

    global avoid_reuse_container, tensor_map, nodes, initializers, enable_trace
    avoid_reuse_container = []
    tensor_map = {}
    nodes = []
    initializers = []

    print("Tracing model inference...")
    print("> Do inference...")
    import pdb;pdb.set_trace()
    with torch.no_grad():
        register_tensor(voxels)
        enable_trace = True
        y = model(voxels, coors, batch_size, spatial_shape)[0]      # Here is the error!!!
        enable_trace = False
```

The error message is as follows.

```Python
 --> SparseConvolution0[subm] -> Input 0, Output 1
   --> SparseConvolution1[subm] -> Input 1, Output 2
   --> SparseConvolution2[subm] -> Input 2, Output 3
   --> Add0 -> Input 3 + 1, Output 4
   --> ReLU0 -> Input 4, Output 5
   --> SparseConvolution3[subm] -> Input 5, Output 6
   --> SparseConvolution4[subm] -> Input 6, Output 7
   --> Add1 -> Input 7 + 5, Output 8
   --> ReLU1 -> Input 8, Output 9
   --> SparseConvolution5[conv] -> Input 9, Output 10
Traceback (most recent call last):
  File "onnx_export/export-scn.py", line 89, in <module>
    exptool.export_onnx(model, voxels, coors, batch_size, spatial_shape, args.save_onnx, args.save_tensor)
  File "/data/pointcloud_alg/Lidar_AI_Solution-master/CenterPoint-master/onnx_export/exptool.py", line 329, in export_onnx
    with torch.no_grad():
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/pointcloud_alg/Lidar_AI_Solution-master/CenterPoint-master/./det3d/models/backbones/scn.py", line 173, in forward
    x_conv2 = self.conv2(x_conv1)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/spconv/pytorch/modules.py", line 138, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/pointcloud_alg/Lidar_AI_Solution-master/CenterPoint-master/onnx_export/exptool.py", line 61, in internal_forward
    bind_fn(self, ilayer, y, *args)
  File "/data/pointcloud_alg/Lidar_AI_Solution-master/CenterPoint-master/onnx_export/exptool.py", line 116, in symbolic_sparse_convolution
    helper.make_node(
  File "/opt/conda/lib/python3.8/site-packages/onnx/helper.py", line 109, in make_node
    node.attribute.extend(
  File "/opt/conda/lib/python3.8/site-packages/onnx/helper.py", line 110, in <genexpr>
    make_attribute(key, value)
  File "/opt/conda/lib/python3.8/site-packages/onnx/helper.py", line 394, in make_attribute
    raise TypeError(
TypeError: value "None" is not valid attribute data type.
```

### 2. export_neck_head.py (Sucess)

This module has run successfully

***
Do you know how to solve this problem？

**Comment by chenxyyy** [comment]
This is my understanding of the process of using `CUDA-Centerpoint`
1. train dataset，get the weight.
2. `python export-scn.py` get `centerpoint.scn.onnx`; `python export_neck_head.py` get `rpn_centerhead_sim.onnx`
3. build trt model
4. build the `CUDA-Centerpoint`

**Comment by hopef** [comment]
When constructing onnx node, the attribute value of None is not allowed.
Your process is correct. But your pth file may be different from the one we generated.

**Comment by chenxyyy** [comment]
This `pth` file was trained on Nuscense using the [centerpoint project](https://github.com/tianweiy/CenterPoint)

The commond shows below. 

```
python tools/create_data.py nuscenes_data_prep --root_path="/path/to/nuScenes-mini/" --version="v1.0-mini" --nsweeps=10

python ./tools/train.py configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py
```
Is there any problem with this operation?

**Comment by hopef** [comment]
Please help me to check which of the `xxx` attributes mentioned in the following code `self.xxx` in your model is `None`?

```python  
nodes.append(
      helper.make_node(
          "SparseConvolution", inputs, [get_tensor_id(y)], f"conv{ilayer}", 
          ndim = self.ndim,
          input_spatial_shape = x.spatial_shape,
          output_spatial_shape = y.spatial_shape,
          in_channels = self.in_channels,
          out_channels = self.out_channels,
          kernel_size = self.kernel_size,
          output_bound = output_bound,
          stride = self.stride,
          dilation = self.dilation,
          padding = self.padding,
          transposed = self.transposed,
          inverse = self.inverse,
          output_padding = self.output_padding,
          groups = self.groups,
          subm = self.subm,
          rulebook = self.indice_key,
          activation = act_type_name[self.act_type],
          input_shape  = x.features.shape,
          output_shape = y.features.shape
      )
  )
```

**Comment by chenxyyy** [comment]
Yes. `self.indice_key` is `None`.

I have tried the `pth` file  [epoch_20.pth](https://mitprod-my.sharepoint.com/:f:/g/personal/tianweiy_mit_edu/EhgzjwV2EghOnHFKyRgSadoBr2kUo7yPu52N-I3dG3c5dA?e=a9MdhX) offered in `3DSparseConvolution` module. It didn't work either.

**Comment by hopef** [comment]
Maybe you can modify the following code to solve this problem.

```python
nodes.append(
      helper.make_node(
          "SparseConvolution", inputs, [get_tensor_id(y)], f"conv{ilayer}", 
          ndim = self.ndim,
          input_spatial_shape = x.spatial_shape,
          output_spatial_shape = y.spatial_shape,
          in_channels = self.in_channels,
          out_channels = self.out_channels,
          kernel_size = self.kernel_size,
          output_bound = output_bound,
          stride = self.stride,
          dilation = self.dilation,
          padding = self.padding,
          transposed = self.transposed,
          inverse = self.inverse,
          output_padding = self.output_padding,
          groups = self.groups,
          subm = self.subm,
          rulebook = self.indice_key if self.indice_key else "",
          activation = act_type_name[self.act_type],
          input_shape  = x.features.shape,
          output_shape = y.features.shape
      )
  )
```

**Comment by chenxyyy** [comment]
Very good, the `CUDA-Centerpoint` process has been fully completed. Next, I will try to test the accuracy on Nuscense-dataset.

Thank you.

**Comment by hopef** [comment]
It is worth noting that the `submanifold convolution` must care about the `indice_key` setting. 
Because it can lead to a `9 ms` performance improvement on ORIN.

**Comment by kellenf** [comment]
Can you show your onnx graph? thanks!

**Comment by mx2013713828** [comment]
hello,can you share some advices about export .pth to .onnx? 
Do I have to use the parameter "nusc_centpoint_voxelnet_0075voxel_fix_bn_z" for training? 
I want to train a custom model with custom dataset, can you give me some advices about the pipeline?
thank you very much!
