### ISSUE TITLE
Error when  run export-scn.py 

### ISSUE THREAD

**Issue by lix19937** [NVIDIA-AI-IOT/Lidar_AI_Solution#98]
https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/CUDA-CenterPoint  In CUDA-CenterPoint  prodect, 
I run  `python onnx_export/export-scn.py  --save-onnx=ptq.onnx --use-quantization   # --ckpt=ptq.pth`    

```


> Do inference...
   --> SparseConvolutionQunat0[subm] -> Input 0, Output 1
Traceback (most recent call last):
  File "onnx_export/export-scn.py", line 89, in <module>
    exptool.export_onnx(model, voxels, coors, batch_size, spatial_shape, args.save_onnx, args.save_tensor)
  File "~/CenterPoint/onnx_export/exptool.py", line 331, in export_onnx
    y = model(voxels, coors, batch_size, spatial_shape)[0]
  File "~/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "./det3d/models/backbones/scn.py", line 173, in forward
    x = self.conv_input(ret)
  File "~/anaconda3/envs/centerpoint/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "~/CenterPoint/onnx_export/exptool.py", line 61, in internal_forward
    bind_fn(self, ilayer, y, *args)
  File "~/CenterPoint/onnx_export/exptool.py", line 200, in symbolic_sparse_convolution_quant
    input_dynamic_range  = self.input_quantizer.amax.cpu().item(),
AttributeError: 'NoneType' object has no attribute 'cpu'

```

**Comment by lix19937** [comment]
@hopef  yes, if add `--ckpt=ptq.pth`  , will run ok.
